[package]
name = "rust-proxy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1", features = ["full"] }
futures = { version = "0.3.0", features = ["thread-pool"]}
bb8 = "0.8.0"
async-trait = "0.1"
