[package]
name = "rust-proxy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"
clap = { version = "4.1.1", features = ["derive"] }
env_logger = "0.9.0"
backtrace = "0.3.67"

async-trait = "0.1"
tokio = { version = "1.0.0",  features = ["full", "tracing"] }
futures = { version = "0.3.0", features = ["thread-pool"]}
bb8 = "0.8.0"
tokio-util = { version = "0.7.0",  features = ["full"] }
