version: '3.9'

services:
  test:
    image: demisto/rakyll-hey:1.0.0.44140
    tty: true 
    deploy:
      resources:
        limits:
          cpus: "4.0"
          memory: 8192M
  backend:
    image: jmalloc/echo-server
    ports:
    - "9394:8080"
    deploy:
      resources:
        limits:
          cpus: "4.0"
          memory: 8192M
  traefik:
    image: traefik:v2.9.8
    container_name: traefik
    volumes:
    - ./dynamic_conf.toml:/etc/traefik/dynamic_conf.toml
    - ./traefik.toml:/etc/traefik/traefik.toml
    restart: unless-stopped
    ports:
      - 80:80
    deploy:
      resources:
        limits:
          cpus: "4.0"
          memory: 8192M
