version: '3.9'
services:
  test:
    image: demisto/rakyll-hey:1.0.0.44140
    tty: true 
    deploy:
      resources:
        limits:
          cpus: "4.0"
          memory: 8192M
  backend:
    image: jmalloc/echo-server
    mem_limit: 8192m
    deploy:
      resources:
        limits:
          cpus: "4.0"
          memory: 8192M
    ports:
    - "9394:8080"
  caddy:
    image: caddy:2.6.4
    mem_limit: 8192m
    ports:
      - "8050:80"
    volumes:
      - ./caddyfile:/etc/caddy/Caddyfile
    deploy:
      resources:
        limits:
          cpus: "4.0"
          memory: 8192M